### ISSUE TITLE
Responsive maken > zie Figma bestand

### ISSUE THREAD

**Issue by Lmikkers** [Lmikkers/proof-of-concept#5]

**Comment by Lmikkers** [comment]
Website responsive gemaakt voor op tablet:

``` css
/* -----RESPONSIVE ----------------------------------------------------------------------------------------------------------------------- */
/* tablet */
@media (max-width: 1024px) {
    .scanResults {
        grid-template-columns: 1fr;
        grid-template-rows: auto;
    }
    .autoScanResult {
        grid-column: 1 / 3;
        grid-row: 1 / 2;
    }
    .typesErrorChart {
        grid-column: 1 / 3;
        grid-row: 3 / 3;
    }
    #typesErrorChart {
        display: block;
    }
    .resultErrors {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: var(--spaceUnit);
        grid-column: 1 / 3;
        grid-row: 2 / 3;
    }
}
```
